spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5m

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: "/api/researchers-managements"
logging:
  level:
    com.tribu.interview: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

github:
  api:
    token: ${GITHUB_TOKEN}


